
function display(B)

disp('Bloque DMRG:')
disp('Longitud del bloque =')
disp(B.l)
disp('Dimension del bloque =')
disp(B.dim)
disp('Hamiltoniano del bloque =')
disp(B.HB)
disp('S+ del extremo del bloque =')
disp(B.Spb)
disp('Sz del extremo del bloque =')
disp(B.Szb)
disp('Matriz de transformacion al siguiente bloque =')
disp(B.O)